---
- hosts: all
  gather_facts: False

  tasks:
  - name: install python 2
    become: yes
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Build a Rails development environment
  hosts: web
  become: yes

  roles:
    - nodejs
