- name: Install Node.js
  apt: name={{ item }} state=latest
  with_items:
    - nodejs
    - npm

- name: cache clean
  command: npm cache clean
  with_first_found:
    - files:
      - /usr/local/bin/node
      skip: true

- name: install n
  command: npm install n -g
  with_first_found:
    - files:
      - /usr/local/bin/node
      skip: true

- name: n stable
  command: n stable
  with_first_found:
    - files:
      - /usr/local/bin/node
      skip: true

- name: Install Node.js with n package
  command: ln -sf /usr/local/bin/node /usr/bin/node
  with_first_found:
    - files:
      - /usr/local/bin/node
      skip: true

- name: Uninstall old packages
  apt: >
    pkg={{ item }}
    state=absent
    purge=yes
    force=yes
  with_items:
    - nodejs
    - npm
