- name: Install Node.js
  apt: name={{ item }} state=latest
  with_items:
    - nodejs
    - npm

- name: cache clean
  command: npm cache clean

- name: install n
  command: npm install n -g

- name: n stable
  command: n stable

- name: Install Node.js with n package
  command: ln -sf /usr/local/bin/node /usr/bin/node

- name: Uninstall old packages
  apt: >
    pkg={{ item }}
    state=absent
    purge=yes
    force=yes
  with_items:
    - nodejs
    - npm
